[GLOBAL]
pants_version = "2.12.1"
backend_packages = [
    "pants.backend.shell",
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.docker",
    "pants.backend.docker.lint.hadolint",
]

[anonymous-telemetry]
enabled = false

[python]
interpreter_constraints = ["CPython==3.10.*"]
